apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: epmd
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: cluster-rpc
      port: 25672
      protocol: TCP
      targetPort: 25672
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
