name: Build images
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [listener-service, mailer-service, logger-service, authentication-service, broker-service, front-end]
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo ${{ secrets.TOKEN }} | docker login ghcr.io -u ${{github.actor}} --password-stdin
        docker build -t ${{ matrix.service }}:latest -f ./${{ matrix.service }}/Dockerfile ./${{ matrix.service }}/
        docker push ${{ matrix.service }}:latest

    
